add new layout
ESPWortuhr/Multilayout-ESP-Wordclock pull request #102
Opened 2021-05-19 19:17 UTC by killee

Hi,

wie besprochen die Änderungen mit der Implementierung der Anordnung der LEDs mit dem Layout der Frontplatte von: https://www.mikrocontroller.net/articles/Word_Clock

Grüße
Kilian

2021-05-24 21:51 UTC, tali requested changes
Bitte aufteilen und pro Commit nur eine logische Änderung.
Bei Fragen, wie man Commits aufteilen kann, bin ich gerne behilflich.

2021-05-24 21:51 UTC, tali commented on src/Wortuhr.ino
> +            //if (Word_array_old[usedUhrType->getFrontMatrix(row, col)] !=500 ){
Bitte keinen alten Code auskommentiert drin lassen.
Lieber gleich komplett löschen.

2021-05-24 21:51 UTC, tali commented on src/Wortuhr.ino
> +    if (last_sekunde != _sekunde) {
Bitte pro Commit immer nur eine Sache machen und nicht mit Umformatierungen mischen.

2021-05-24 21:51 UTC, tali commented on include/Uhrtypes/Uhrtype.hpp
> +
Bitte nicht Features und Umformatierungen in einem Commit mischen.

2021-05-24 21:51 UTC, tali commented on include/Uhrtypes/uhr_func_114_mc.hpp
> +    const uint8_t *marix = &matrix_button_left[0][0];
`marix`?

2021-05-24 21:51 UTC, tali commented on include/Uhrtypes/uhr_func_114_mc.hpp
> +        {*(marix + (10 * 11 + 0)), *(marix + (10 * 11 + 1)), *(marix + (10 * 11 + 2)), *(marix + (10 * 11 + 3))},
Arrays bitte richtig indizieren und nicht mit Pointer-Arithmetik rumrechnen.

2021-05-31 17:02 UTC, killee commented on src/Wortuhr.ino
> +            //if (Word_array_old[usedUhrType->getFrontMatrix(row, col)] !=500 ){
Ja hast recht. Teile das noch auf... Dauert aber noch ein wenig.
Räume dann generell auf.

2021-06-02 06:34 UTC, dbambus commented
@killee Ich würde gerne einen Release 2.6.1 bauen wollen, ehe größere Änderungen am Unterbau kommen. Daher wäre es super, wenn du diesen PR, wenn auch nur mit dem neunen Layout fertig bekommst :-) 

Dann können wir gemeinsam weiter an neuen Features arbeiten :-)

2021-06-07 11:22 UTC, dbambus commented on webpage/index.html
> +                                        <option value="9" selected>Uhr 114 MC</option>
Beide Optionen als 'selected'  ?

2021-06-14 13:26 UTC, killee commented
@dbambus sorry war zu eingespannt...
Wird die Woche mit tollen Wetter und offenen Biergärten nicht besser.
Denke aber das es mit der neuen Idee sowieso obsolet ist.
Würde dann da gleich noch mal das Layout erstellen und ein PR machen.
Ist das Okay?

2021-06-14 14:40 UTC, dbambus commented
Das ist völlig okay, auch ich komm nur während der Arbeit etwas zum lesen und coden. Abends bin ich selbst unterwegs und helfe mit Hopfenkaltschorlen nach.

2023-07-01 22:28 UTC, closed without merging