Show IP address if NTP server has no name
ESPWortuhr/Multilayout-ESP-Wordclock pull request #52
Opened 2021-01-27 18:58 UTC by tali

This fixes a crash when `sntp_getservername()` returns `nullptr`.

2021-01-27 23:37 UTC, ATho95 commented
So sah auch mein erster Ansatz aus. Allerdings legt IPAdress.toString den Buffer auf dem Stack an und da werden die ersten Bytes überschrieben. Deshalb hatte ich den strcpy eingebaut. Der ist in diesem Fall notwendig.

2021-01-28 06:58 UTC, tali commented
OK, so ganz klar ist mir noch nicht, warum `strcpy` funktioniert und `printf` nicht, aber wenn wir uns stattdessen den `String` speichern dann müssen wir da nix manuell kopieren. Funktioniert das jetzt bei dir?

2021-01-28 07:50 UTC, dbambus commented
Hey, 

ich habe gestern auch mal den Stacktrace, meines Reboot Problems angeschaut. Hier bekomme ich: 

`Fatal exception (28):epc1=0x4025bfa6, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000000f, depc=0x00000000` 

Dieser Fehler kommt Zustande, wenn ein Nullptr zum lesen an das pgm_read_byte_inline geschickt wird. Ich hatte aber eher vermutet, dass es im Zusammenhang mit dem WiFiManager kommt. Da es immer im Stage WiFi beginnt, komisch dabei ist, dass nach einer Minute ungefähr die Uhr aus dem Loop geht und tatsächlich funktioniert. Oder ist euer Commit eher die Lösung dafür ? 

Nichts desto trotz wäre ich eher dafür die Mayorreleases vom WiFiManager zu verwenden, sprich v0.16 anstatt den aktuellen `master` Branch vom Repo.

2021-01-28 08:55 UTC, ATho95 requested changes
Sorry, gestern abend war es wohl ein bischen spät
Wenn du jetzt noch
   if (!origin) {
mit
   if (origin.length() == 0) {
tauschst funktionierts.

2021-01-28 09:04 UTC, ATho95 commented
@dbambus 
dein Stacktrace passt zu diesem Fehler. Er kommt aus der WiFi, weil der Callback von da aus aufgerufen wird.
Dass der Fehler verschwindet hatte ich auch. Ich vermute, dass hängt mit Laufzeiten zusammen. Wenn der NTP Server noch nicht geantwortet hatte, wird "SNTP not reachable" statt dem NULL Pointer via printf ausgegeben.

2021-01-28 09:46 UTC, dbambus approved these changes

2021-01-28 11:04 UTC, dbambus commented
Okay, 

ich werde es mal testen. :-) hat einer von euch beiden eigentlich mal den ESP [GDB](https://arduino-esp8266.readthedocs.io/en/latest/gdb.html) zum debuggen verwendet ?

2021-01-28 13:45 UTC, ATho95 commented
@dbambus, deine Frage hat mich veranlasst, den GDB nochmal mit 57600 Baud zu testen. Ich hatte vorher mit 115200 ständig Abbrüche. Aber damit geht's. Allerdings muss Neopixel ausgebaut werden da sich der Dout Pin mit dem UART RX Pin überschneidet. Man kann natürlich auch, so wie ich es mache, einzelne Funktionen in ein separates Project kopieren.
Ich nutze allerdings Eclipse mit Sloeber Plugin. Die Konfiguration ist nämlich die halbe Miete. 
Man muss nur aufpassen, dass man die zu testenden Funktionen ins RAM legt. Der eine HW Breakpoint reicht nicht, um Funktionen, die im Flash liegen zu debuggen. 
![GDB screenshot](https://user-images.githubusercontent.com/40203268/106146709-4b76a000-6177-11eb-8285-b106f1f91612.JPG)

2021-01-28 19:30 UTC, merged